version: '3.11'

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    environment:
      - SECRET_KEY=butatamakq-12-ragaichushkivboba
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=dcddb
      - DB_USER=root
      - DB_PASS=1234
    depends_on:
      - db
  db:
   image: postgres:13
   environment:
      - POSTGRES_DB=dcddb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234